# Generated by Django 4.2.6 on 2023-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharecenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='filename',
            field=models.CharField(default='UNDEFINED', max_length=255),
        ),
    ]
